<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TODOApp.UI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SOSApp.Contract\SOSApp.Contract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.4.0" />
    </ItemGroup>

</Project>
