<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SOSApp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.4.0" />
      <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SOSApp.Contract\SOSApp.Contract.csproj" />
    </ItemGroup>

</Project>
